### ISSUE TITLE
Adding Search to KB

### ISSUE THREAD

**Issue by sneumann** [NFDI4Chem/knowledge_base#119]
Hi, it would be great to have search capabilities across the KB. 
https://docusaurus.io/docs/search has options. Chemotion Docusaurus is using external Algolia at https://chemotion.net/chemotionsaurus/docs/docu/use_docusaurus
We might want a variant of local search to avoid (yet another :-) ) external service. There might be a working example in https://github.com/cmfcmf/docusaurus-search-local
Yours, Steffen

**Comment by ann-christinandres** [comment]
Hi Steffen,
Algolia search will be integrated as a timely solution. We will also check the working example you suggested.
Yours, Ann-Christin
