### ISSUE TITLE
KB search hangs

### ISSUE THREAD

**Issue by sneumann** [NFDI4Chem/knowledge_base#188]
Hi, currently the search-box in the KB hangs, i.e. spinning wheel when you enter any search term. 
No reaction when hitting return. Tested on FireFox, Chrome & Android Chrome from ~3 different networks. 
Yours, Steffen

**Comment by sneumann** [comment]
So, the KB uses https://github.com/easyops-cn/docusaurus-search-local
When entering anything in the search box, it tries to access
https://knowledgebase.nfdi4chem.de/knowledge_base/search-index.json which simply does not exist. 
This *might* be similar to https://github.com/easyops-cn/docusaurus-search-local/issues/241#issuecomment-1192234431
Yours, Steffen

**Comment by sneumann** [comment]
Hm, Our `'@docusaurus/preset-classic'` in 
https://github.com/NFDI4Chem/knowledge_base/blob/a6e962a8764fa8a458bac0c77c74df3e1b9aa3e8/docusaurus.config.js#L131
has no `routeBasePath:` in it. And further down `'@easyops-cn/docusaurus-search-local'` has no `docsRouteBasePath:` neither. 
OR the generation of search-index.json  simply had failed. 
Yours, Steffen

**Comment by jliermann** [comment]
`easyops-cn/docusaurus-search-local` broke the search in recent versions. Reverted to version 0.22.
Fixed by af1e0490f6ffd4fdef67390c395cf4d8adb9de36.
