### ISSUE TITLE
Knowledgebase LbE DOI redirection BUG

### ISSUE THREAD

**Issue by tditfe** [NFDI4Chem/knowledge_base#239]
I get redirected to the wrong paper when I click on the DOI of an publication after utilizing the permalink function.

---How to reproduce---

Knowledgebase  -> LbE -> Click on Permalink of any other Paper but the "Linderazulen aus einer invasiven Pflanze - Delphi und sein violettes Wunder"  -> in the new tab click on the DOI of the Paper -> get redirected to the Linderazulen Paper (for all the tested papers)

**Comment by jliermann** [comment]
That is actually not a bug in the React component but a bizarre effect of the deployment build: The variable has the correct value at this point, but the html tag with the link does not get re-rendered. The same problem occurs for the first repo link. I will see if I can find a workaround.

**Comment by jliermann** [comment]
The wrong link is an artifact from the previous rendering of the first LBE dataset. The same happens for the first data link, respectively. I included code to force-update the respective a.href node, it does not seem elegant to me but it works.

**Comment by jliermann** [comment]
After diving somewhat deeper into React principles I found a better way to solve this with the `useEffect()` hook.
