### ISSUE TITLE
Dead link in ontology article

### ISSUE THREAD

**Issue by Brilator** [NFDI4Chem/knowledge_base#263]
The DOI in line 17 (https://github.com/NFDI4Chem/knowledge_base/edit/main/docs/40_topics/50_ontology.mdx) prompts a `504 ERROR The request could not be satisfied.`

**Comment by Brilator** [comment]
I guess it's supposed to refer to https://www.degruyter.com/document/doi/10.1515/pac-2021-2007/html?

**Comment by jliermann** [comment]
I am sorry, I cannot reproduce the problem, the Link contains the right URL and works for me. HTTP Error 504 is not typical for wrong or malformed links, is it possible that you had temporal connection issues on your side?

![grafik](https://user-images.githubusercontent.com/40795855/217537797-61dd8c5e-823c-4159-8009-f5eabf708ad2.png)

**Comment by Brilator** [comment]
Ouch. Sorry for that.
