### ISSUE TITLE
bilingual knowledge base (English, German)

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/knowledge_base#266]
Die Knowledge Base sollte auch auf deutsch verfügbar sein, wie auf der Klausurtagung besprochen, damit wir weitere Gruppen von Menschen mit den Inhalten erreichen.

**Comment by jliermann** [comment]
Created prototype in branch [266-bilingual-knowledge-base-english-german](https://github.com/NFDI4Chem/knowledge_base/tree/266-bilingual-knowledge-base-english-german).

Edit German docs under:
`/i18n/de/docusaurus-plugin-content-docs/current/`

**Caution**: Language switching using the pull down menu in the navbar does not work when using the development runtime (`npm run start`). To examine the German locale, use `npm run start -- --locale de` instead.

**Comment by jliermann** [comment]
Initial prototype build (with working language switch) here:
https://knowledgebase.nfdi4chem.de/staging_i18n/knowledge_base/

**Comment by jliermann** [comment]
The staging site under
https://knowledgebase.nfdi4chem.de/staging_i18n/knowledge_base/

is currently rebuilt twice a day at 6:00 and 18:00, so you can actually see your changes with a delay once they have been merged into the working branch.
