### ISSUE TITLE
German language edition on mobile devices

### ISSUE THREAD

**Issue by tilfischer** [NFDI4Chem/knowledge_base#315]
Dear all,

with bigger screens, I can select English or Deutsche at the very top. With smaller screens this is not shown, hence, language cannot be changed. 

Best,
Tillman

**Comment by jliermann** [comment]
For small / mobile screens, the language switch collapses with the main menu. See screenshots below. Please reopen if any questions remain.

![grafik](https://github.com/NFDI4Chem/knowledge_base/assets/40795855/708d73c5-3851-43f2-8ccc-b1bb8c8e6b7f)
![grafik](https://github.com/NFDI4Chem/knowledge_base/assets/40795855/6bd2df26-a734-4de0-98e4-d3c3a74ed46d)
