### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by jliermann** [NFDI4Chem/knowledge_base#411]
https://knowledgebase.nfdi4chem.de/staging_eln/knowledge_base/docs/choose_eln/

- [x] Remove link to LabTrove, leads to junk sites.
- [x] Run general link check, fix internal links

**Comment by Ted-Bender** [comment]
LabTrove-Link corrected to sourceforge-Quelle

**Comment by jliermann** [comment]
@nicolejung
